### ISSUE TITLE
ShardingCore项目路径问题

### ISSUE THREAD

**Issue by dafeifei0218** [xuejmnet/ShardingWithFramework#1]
\abp\toapp\TodoApp.sln解决方案的ShardingCore项目是引用作者本机的，需要改为nuget包或放在此项目中吧，否则还需要下载ShardingCore项目，并重新添加项目。

**Comment by xuejmnet** [comment]
@dafeifei0218 实在不好意思上次调试忘记了我这边修复一下谢谢

**Comment by xuejmnet** [comment]
您也可以直接引用nuget一样的

**Comment by xuejmnet** [comment]
已经修复
